import HeroImage from './HeroImage'
import TestmonialsImage from './TestmonialsImage'
import TestmonialsData from './TestmonialsData'
import DetailsHero from './DetailsPageHero'
import LandingHeroForm from './LandingHeroForm'
import AboutDetails from './AboutDetails'
import BookingDetails from './BookingDetails'
import RatingDetails from './RatingDetails'
import CustomTable from './CustomTable'
import ADSRoom from './ADSRoomCard'
import LargeRoom from './LargeRoom'
import Charts from './Charts'
import CommentDetails from './CommentDetails'

export { HeroImage, TestmonialsImage, TestmonialsData, DetailsHero, LandingHeroForm, AboutDetails, BookingDetails, RatingDetails, CustomTable, ADSRoom, LargeRoom, Charts, CommentDetails }
